### ISSUE TITLE
ModuleNotFoundError: No module named 'message'

### ISSUE THREAD

**Issue by fdurantelp** [swimlane/graphish#7]
In my script I have the following includes:
```
from graphish import GraphConnector
from graphish import Search
```
I get this error:
`Traceback (most recent call last):
  File "graph-test.py", line 1, in <module>
    from graphish import GraphConnector
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/graphish-1.3.0-py3.8.egg/graphish/__init__.py", line 2, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/graphish-1.3.0-py3.8.egg/graphish/search.py", line 1, in <module>
ModuleNotFoundError: No module named 'message'`

I'm using Ubuntu 20.04 with python 3.8.10.  I tried Graphish from PIP install and I have tried from cloning the source and compiling with "python setup.py install".  Both result with the same missing module.  However, message.py clearly exists in the graphish folder.

Any ideas how I can resolve this?  It appears the search.py module imports the message.py module so I shouldn't need to import in my code, but I did try to import it too.  No success.

My code in question:
```
from graphish import GraphConnector
from graphish import Search

connector = GraphConnector(
    clientId='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    clientSecret='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    tenantId='XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
)

search = Search(connector)

new_search = search.create(
    searchFolderName='Phishing Search',
    sourceFolder='inbox',
    filterQuery="contains(subject, 'EXPIRES')"
)

# get all the messages in your search folder

for message in search.messages():
    print(message) # Returns all attributes from a message
    print(message['id']) # returns the message ID
    print(message['headers']) # Returns the RFC822 headers of the message
    

```

**Comment by fdurantelp** [comment]
Same issue goes for Ursers module.

The Users module and Messages module are using names that are assumed for a more prevalent library.  I fixed the bug by editing search.py to import the two ubiquitous classes explicitly to graphish.

Go to the search.py file and edit line #1 and #2 to be as follows:
```
from graphish.message import Message
from graphish.users import Users

```

**Comment by MSAdministrator** [comment]
I updated this to support Python 3.6 and greater only which should resolve your issues.
